<%@ Page Title="" Language="C#" MasterPageFile="~/Admin_master.master" AutoEventWireup="true" CodeFile="Add_course.aspx.cs" Inherits="Add_course" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <style type="text/css">
        .style4
        {
            width: 361px;
        }
        .style5
        {
            width: 155px;
        }
        
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
 <center>
    <table class="style1" style="width:50%; height:300px;" cellpadding="5px" 
        cellspacing="5px">
        <tr align="center">
            <td colspan="2" style="height: 83px">
                <h2 style="text-decoration: underline">Add Course</h2>
                <p>&nbsp;</p>
            </td>
          </tr>  
        <tr >
            <td  align="right" class="style5" style="font-size:17px; padding-bottom:20px" >
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <strong>Course</strong>
            </td>
            <td style="width: 285px">
             &nbsp&nbsp;&nbsp;&nbsp;&nbsp; &nbsp <asp:TextBox ID="coursenm" runat="server" Height="30px" Width="231px" 
                    Font-Bold="True" ></asp:TextBox>
                    <br />
                    <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" 
                    ControlToValidate="coursenm" ErrorMessage="*Enter Course Name" 
                    ForeColor="Red" Font-Size="Smaller" ValidationGroup="Validation"></asp:RequiredFieldValidator>
            </td>
        </tr>
          
            
        
        <tr align="center">
            <td colspan="2" align="center" style="height: 50px" class="style4">
                <asp:Button ID="Add" runat="server" Font-Bold="True" Height="40px" Text="Add" 
                    Width="150px" onclick="Add_Click" BackColor="#00AC9C" BorderColor="White" 
                    Font-Size="Large" ForeColor="White" ValidationGroup="Validation" />
                <br />
            </td>
           
        </tr>
        <tr align="center">
            <td colspan="2" align="center" style="height: 31px" class="style4">
                <asp:Label ID="Label1" runat="server" ForeColor="Red"></asp:Label>
               
            </td>
           
           
        </tr>
        <tr align="center">
            <td colspan="2" align="center">
                 <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" 
                     CellPadding="4" DataSourceID="SqlDataSource1" ForeColor="#333333" 
                     GridLines="None" AllowPaging="True" PageSize="5" 
                     AutoGenerateDeleteButton="True" AllowSorting="True" DataKeyNames="CID" 
                     AutoGenerateEditButton="True" Width="400px">
                     <AlternatingRowStyle BackColor="White" />
                     <Columns>
                         <asp:BoundField DataField="CID" HeaderText="Course ID" InsertVisible="False" 
                             ReadOnly="True" SortExpression="CID" >
                         <HeaderStyle Font-Underline="False" />
                         <ItemStyle Font-Underline="False" HorizontalAlign="Center" 
                             VerticalAlign="Middle" />
                         </asp:BoundField>
                         <asp:BoundField DataField="CourseName" HeaderText="Course Name" 
                             SortExpression="CourseName" >
                         <ItemStyle HorizontalAlign="Center" VerticalAlign="Middle" />
                         </asp:BoundField>
                     </Columns>
                     <EditRowStyle BackColor="#7C6F57" />
                     <FooterStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
                     <HeaderStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
                     <PagerStyle BackColor="#666666" ForeColor="White" HorizontalAlign="Center" />
                     <RowStyle BackColor="#E3EAEB" />
                     <SelectedRowStyle BackColor="#C5BBAF" Font-Bold="True" ForeColor="#333333" />
                     <SortedAscendingCellStyle BackColor="#F8FAFA" />
                     <SortedAscendingHeaderStyle BackColor="#246B61" />
                     <SortedDescendingCellStyle BackColor="#D4DFE1" />
                     <SortedDescendingHeaderStyle BackColor="#15524A" />
                 </asp:GridView>
                 <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
                     ConnectionString="<%$ ConnectionStrings:ConnectionString %>" 
                     SelectCommand="SELECT * FROM [course]" 
                     InsertCommand="INSERT INTO [course] ([CourseName]) VALUES (@CourseName)"
                     DeleteCommand="DELETE FROM [course] where [CID]=@CID"
                     UpdateCommand="UPDATE [course] set [CourseName]=@CourseName where [CID]=@CID">
                     <InsertParameters>
                         <asp:Parameter Name="CourseName" Type="String" />
                     </InsertParameters>
                 </asp:SqlDataSource>
            </td>
           
        </tr>
        <tr align="center">
            <td colspan="2" align="center">
                 &nbsp;</td>
           
        </tr>
    </table>
    </center>
    <div>

    </div>
    <br />
</asp:Content>

